### PR TITLE
Updated README.md file

### PR DESCRIPTION
**Pull request by commitSai**

### CODE REVIEW

**Comment by hussein1571** [comment]
Hello commit Sai 

I am trying to test Commithub app , in the step 7 of Pull request to Commit testnet repo  (pull request to repo git status ) I didn't understand [ git commit -m {moniker}  as validator ]

I don't know what should I fill inside moniker 

Could you help me please ?

**Comment by commitSai** [comment]
Hello hussein1571,

>  I didn't understand [ git commit -m {moniker} as validator ]
This is the git commit that specifies us about your validator Info. The
moniker is the name of your validator [that you used when you init using
maind].

And you are using the *crust-1. *I suggest you switch to *crust-2*

if you face any error please ping us.

Thanks& Regards
Sai

**Comment by hussein1571** [comment]
Hello @commitSai .
In fact when I use git push origin I see this error.
root@ausy-OptiPlex-3020:~/go/src/github.com/commitHub/commitBlockchain/genesisTransactions/crust-2# git push origin crust2
**error: le spécificateur de référence source crust2 ne correspond à aucune référence
error: impossible de pousser des références vers 'https://github.com/commitHub/genesisTransactions.git'**

Could you help me please ?
Best regards

**Comment by felicisfelix** [comment]
> root@ausy-OptiPlex-3020:~/go/src/github.com/commitHub/commitBlockchain/genesisTransactions/crust-2# git push origin crust2
> **error: le spécificateur de référence source crust2 ne correspond à aucune référence error: impossible de pousser des références vers 'https://github.com/commitHub/genesisTransactions.git'
- check `git status` once
- Make sure that your in `crust-2`  branch

**Comment by commitSai** [comment]
> root@ausy-OptiPlex-3020:~/go/src/github.com/commitHub/commitBlockchain/genesisTransactions/crust-2# git push origin crust2
> **error: le spécificateur de référence source crust2 ne correspond à aucune référence error: impossible de pousser des références vers 'https://github.com/commitHub/genesisTransactions.git'**

- check `git status`
- make sure  that you're in `crust-2` branch
> if not in **crust-2**, use that head to push the code
> `git push origin HEAD:crust-2`

**Comment by hussein1571** [comment]
Helloroot@ausy-OptiPlex-3020:~/go/src/github.com/commitHub/commitBlockchain/genesisTransactions/crust-2# git push origin HEAD:crust-2
**Username for 'https://github.com': hussein1571
Password for 'https://hussein1571@github.com': 
remote: Permission to commitHub/genesisTransactions.git denied to hussein1571.
fatal: impossible d'accéder à 'https://github.com/commitHub/genesisTransactions.git/' : The requested URL returned error: 403**

------------------------unfortunately it doesn't work :( 

**git status :** 


root@ausy-OptiPlex-3020:~/go/src/github.com/commitHub/commitBlockchain/genesisTransactions/crust-2# git status
Sur la branche master
Votre branche est à jour avec 'origin/master'.

Modifications qui seront validées :
  (utilisez "git restore --staged <fichier>..." pour désindexer)
	nouveau fichier : gentx-85ec07260d225ce1d6b8c0a6cc5ffd9c0c44f68d.json

**git commit:** 


root@ausy-OptiPlex-3020:~/go/src/github.com/commitHub/commitBlockchain/genesisTransactions/crust-2# git commit -m "Commit as genesis validator"

*** Veuillez me dire qui vous êtes.

Lancez

  git config --global user.email "Vous@exemple.com"
  git config --global user.name "Votre Nom"

pour régler l'identité par défaut de votre compte.
Éliminez --global pour ne faire les réglages que dans ce dépôt.

**Pull request closed without merging**
